# yaml-language-server: $schema=https://raw.githubusercontent.com/mui/mui-toolpad/v0.1.42/docs/schemas/v1/definitions.json#properties/Page

apiVersion: v1
kind: page
spec:
  alias:
    - 1VpqniH
  title: Default page
  content:
    - component: Text
      name: text
      props:
        value: Records with user uploaded images
        variant: h4
    - component: DataGrid
      name: dataGrid
      props:
        rows: null
        columns:
          - field: id
            type: string
            width: 185
          - field: projectName
            type: string
            headerName: Project Name
            width: 172
          - field: uploadImages
            type: string
            width: 227
            headerName: Upload image(s)
          - field: file
            type: image
            width: 266
            headerName: File (from Images)
        height: 374
        rowsSource: dataProvider
        dataProviderId: airtableListings.ts:default
        rowIdField: id
    - component: Text
      name: text5
      props:
        variant: h4
        value:
          $$jsExpression: |
            dataGrid.selection?.id ? `Listing ${dataGrid.selection.id}` : ""
    - component: Container
      name: container
      children:
        - component: PageRow
          name: pageRow1
          props:
            justifyContent: start
          children:
            - component: Container
              name: container1
              layout:
                columnSize: 1
              props:
                visible:
                  $$jsExpression: |
                    Boolean(dataGrid.selection?.id)
              children:
                - component: Text
                  name: text1
                  layout:
                    columnSize: 1
                  props:
                    value:
                      $$jsExpression: |
                        `Locally uploaded images`
                    variant: h5
                - component: List
                  name: list
                  props:
                    itemCount:
                      $$jsExpression: |
                        dataGrid.selection?.uploadImages.length
                    sx: null
                    renderItem:
                      $$template:
                        - component: PageRow
                          name: pageRow
                          props:
                            justifyContent: start
                          children:
                            - component: Text
                              name: text2
                              props:
                                mode: markdown
                                value:
                                  $$jsExpression: >
                                    `Airtable Image ID:
                                    __${dataGrid.selection?.uploadImages[i].id}__`
                            - component: Image
                              name: image
                              props:
                                src:
                                  $$jsExpression: |
                                    dataGrid.selection?.uploadImages[i].url
                                fit: contain
                                width: 400
            - component: Container
              name: container2
              layout:
                columnSize: 1
              props:
                visible:
                  $$jsExpression: |
                    Boolean(dataGrid.selection?.["File (from Images)"])
              children:
                - component: PageRow
                  name: pageRow3
                  props:
                    justifyContent: start
                  children:
                    - component: PageColumn
                      name: pageColumn
                      layout:
                        columnSize: 1
                      children:
                        - component: Text
                          name: text3
                          layout:
                            columnSize: 1
                          props:
                            value: AWS uploaded images
                            variant: h5
                        - component: List
                          name: list1
                          props:
                            itemCount:
                              $$jsExpression: |
                                dataGrid.selection?.["Upload image(s)"].length
                            sx:
                              $$jsExpression: >
                                {
                                  display: dataGrid?.selection?.id ? `block` : "none"
                                }
                            renderItem:
                              $$template:
                                - component: PageRow
                                  name: pageRow2
                                  props:
                                    justifyContent: start
                                  children:
                                    - component: Text
                                      name: text4
                                      props:
                                        mode: markdown
                                        value:
                                          $$jsExpression: >
                                            `AWS S3 URL:
                                            __${dataGrid.selection?.["File (from
                                            Images)"][i]}__`
                                    - component: Image
                                      name: image1
                                      layout:
                                        columnSize: 1
                                      props:
                                        src:
                                          $$jsExpression: >
                                            dataGrid.selection?.["File (from
                                            Images)"][i]
                                        fit: contain
                                        width: 400
    - component: Button
      name: button
      props:
        content: Upload to S3
        disabled:
          $$jsExpression: |
            !dataGrid.selection?.id ||
              Boolean(dataGrid?.selection?.["File (from Images)"]?.length > 0)
        onClick:
          $$jsExpressionAction: |
            uploadToS3.call();
        loading:
          $$jsExpression: |
            uploadToS3.isLoading
        size: medium
  queries:
    - name: uploadToS3
      mode: mutation
      query:
        function: functions2.ts#default
        kind: local
      parameters:
        - name: airtableListingId
          value:
            $$jsExpression: |
              dataGrid.selection?.id
        - name: airtableUploadedImages
          value:
            $$jsExpression: |
              dataGrid.selection?.uploadImages
