name: Build and Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    environment: bk-one

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: SCP to DigitalOcean droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          source: "./" # Path to your built app
          target: "~/ctfg-toolpad"

      - name: SSH into DigitalOcean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22
          script: |
            cd ~/ctfg-toolpad
            # Check if service file exists
            if [ ! -f /etc/systemd/system/toolpad.service ]; then
              # Create service file only if it doesn't exist
              echo "[Unit]
              Description=Toolpad Application
              After=network.target

              [Service]
              User=${{ secrets.DROPLET_USERNAME }}
              WorkingDirectory=~/ctfg-toolpad
              ExecStart=$(which npm) start
              Restart=always

              [Install]
              WantedBy=multi-user.target" | sudo tee /etc/systemd/system/toolpad.service

              # Enable new service
              sudo systemctl enable toolpad
            fi

            # Restart service
            sudo systemctl restart toolpad
